# Generated by Django 4.0.4 on 2022-04-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='neighbour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
